### PR TITLE
Install CMake export

### PR DESCRIPTION
**Pull request by koprok**
- Add ZINT_SHARED CMake option, so that either shared or static or both libraries can be built.
- Install modern CMake export file for zint library. CMake export for qzint could be added too. This will make the installed FindZint.cmake obsolete.

### CODE REVIEW

**Comment by gitlost** [comment]
Hi, thanks for the PR which looks excellent. However this is a read-only mirror of the Source Forge project https://sourceforge.net/projects/zint/, would you mind opening this as a Merge Request there? Thank you.

**Comment by koprok** [comment]
@gitlost, done.
https://sourceforge.net/p/zint/code/merge-requests/153/

**Comment by gitlost** [comment]
Great stuff, thanks!

**Comment by koprok** [comment]
> Great stuff, thanks!

@gitlost, thank you too for developing this useful library.
FYI, I have contributed a zint port to vcpkg project (https://github.com/microsoft/vcpkg), so that the library can be built and used more easily.

**Comment by gitlost** [comment]
Oh excellent, I notice you needed other changes apart from this to get zint's cmake config to behave.

Re "zintconfig.h" being in the git tree although it's generated from "zintconfig.h.in", this was a hack to get the existing various MSVC  project/solution/workspace files to work. Will remove "zintconfig.h.in" for the next release and just update "zintconfig.h" manually (via "update_version.php" tool), so that should remove the need for "0003-fix-parallel-configure.patch".

Re any further changes needed, would welcome any fixes whenever you have the time.

(Re zint, thank you, but I should mention that Robin Stuart developed it, I'm the current custodian!)

**Comment by koprok** [comment]
@gitlost, thumbs up about zintconfig.h! I will update the vcpkg port after you tag a new version.

> Re any further changes needed, would welcome any fixes whenever you have the time.

I propose to change the NO_PNG define to something less-generic, for example ZINT_NO_PNG. This is necessary because this define is PUBLIC and so it is propagated to everyone who links with the zint::zint target.

Another possibility is to make this define private to zint::zint, but then users will have no way to know if the library supports png or not, right?

**Comment by gitlost** [comment]
I see, yes will do both I think, rename it to ZINT_NO_PNG and make it private, then introduce an API `int Zint_NoPng(void)` function that users can query instead to address your last point.

(The Qt GUI is the only place NO_PNG is used outside of the library so replacing that with the new API will be simple.)

**Pull request merged**
